#!/usr/bin/env python3
"""Build application packages and upload them to bintray.
Works on TravisCI, CircleCI and locally. Detect which package need to be rebuilt.
Support "release" packages and PR/testing.

scan              - scan the current repository for packages to be built
build             - locate and build packages
upload <filename> - upload one package to Bintray
ci                - detect CircleCI PRs, build and upload packages to Bintray
delete_from_bintray <filename> - delete filename from Bintray
"""


# debdeps: git
from argparse import ArgumentParser
from os import getenv
from pathlib import Path
from requests.auth import HTTPBasicAuth
from subprocess import run
from typing import List
import requests
import sys

BINTRAY_API = "https://bintray.com/api/v1"
DEFAULT_ORG = "ooni"
DEFAULT_PR_REPO = "internal-pull-requests"
DEFAULT_MASTER_REPO = "internal-master"
DEFAULT_REPO = "internal-pull-requests"

assert sys.version_info >= (3, 7, 0), "Python 3.7.0 or later is required"


def run2(cmd, **kw):
    p = run(cmd.split(), capture_output=True, **kw)
    if p.returncode != 0:
        raise Exception(f"'{cmd}' returned: {p.returncode}")
    return p.stdout.decode()


def runi(cmd: str, cwd: Path, sudo=False) -> None:
    if sudo:
        cmd = f"sudo {cmd}"
    run(cmd.split(), cwd=cwd, check=True)


def detect_changed_packages() -> List[Path]:
    DCH = "debian/changelog"
    commit = run2("git merge-base master HEAD")
    changes = run2(f"git diff --name-only {commit}")
    pkgs = set()
    for c in changes.splitlines():
        c = Path(c)
        if c.as_posix().endswith(DCH):
            pkgs.add(c.parent.parent)
            continue
        while c.name:
            if c.joinpath(DCH).is_file():
                pkgs.add(c)
            c = c.parent

    return sorted(pkgs)


def trim_compare(url: str) -> str:
    """Shorten GitHub URLs used to compare changes"""
    if url.startswith("https://github.com/") and "..." in url:
        base, commits = url.rsplit("/", 1)
        if len(commits) == 83:
            beginning = commits[0:8]
            end = commits[43 : 43 + 8]
            return f"{base}/{beginning}...{end}"

    return url


def buildpkg(p) -> List[Path]:
    """Build one package, installing required dependencies"""
    print(f"Building package in {p}")
    ver = run2("dpkg-parsechangelog --show-field Version", cwd=p).strip()
    assert ver, f"No version number found in {p}/debian/changelog"
    sudo = True
    if getenv("CIRCLECI"):
        # Running in CircleCI
        sudo = False
        comp = trim_compare(getenv("CIRCLE_COMPARE_URL", ""))  # show changes in VCS
        if not comp:
            # https://discuss.circleci.com/t/circle-compare-url-is-empty/24549/8
            comp = getenv("CIRCLE_PULL_REQUEST")

        if getenv("CIRCLE_PULL_REQUEST"):
            # This is a PR: build ~pr<N>-<N> version. CIRCLE_PR_NUMBER is broken
            pr_num = getenv("CIRCLE_PULL_REQUEST", "").rsplit("/", 1)[-1]
            build_num = getenv("CIRCLE_BUILD_NUM")
            ver = f"{ver}~pr{pr_num}-{build_num}"
            print(f"CircleCI Pull Request detected - using version {ver}")
            run2(f"dch -b -v {ver} {comp}", cwd=p)
            run2(f"dch -r {ver} {comp}", cwd=p)
            ver2 = run2("dpkg-parsechangelog --show-field Version", cwd=p).strip()
            assert ver == ver2, ver + " <--> " + ver2

        elif getenv("CIRCLE_BRANCH") == "master":
            # This is a build outside of a PR and in the mainline branch
            print(f"CircleCI mainline build detected - using version {ver}")
            run2(f"dch -b -v {ver} {comp}", cwd=p)
            run2(f"dch -r {ver} {comp}", cwd=p)
            ver2 = run2("dpkg-parsechangelog --show-field Version", cwd=p).strip()
            assert ver == ver2, ver + " <--> " + ver2

        else:
            # This is a build for a new branch but without a PR: ignore it
            return []

    runi("apt-get build-dep -qy --no-install-recommends .", p, sudo=sudo)
    runi("fakeroot debian/rules build", p)
    runi("fakeroot debian/rules binary", p)
    with p.joinpath("debian/files").open() as f:
        return [p.parent.joinpath(line.split()[0]) for line in f]


def ci(args) -> None:
    # TODO: detect sudo presence
    err = "BINTRAY_USERNAME or BINTRAY_API_KEY environment variables not set"
    assert getenv("BINTRAY_USERNAME") and getenv("BINTRAY_API_KEY"), err
    assert not args.repo, "Do not set repository in automated CI runs"
    run2("apt-get update -q")
    run2("apt-get install -qy --no-install-recommends git")
    pkgdirs = detect_changed_packages()
    if not pkgdirs:
        return
    print(f"Building {pkgdirs}")
    run2("apt-get install -qy --no-install-recommends devscripts")

    pkgs_lists = [buildpkg(pd) for pd in pkgdirs]
    for pli in pkgs_lists:
        for p in pli:
            # Upload all builds to the test repository
            # and master builds to master repository
            upload(p, args, DEFAULT_PR_REPO)
            if not getenv("CIRCLE_PULL_REQUEST"):
                upload(p, args, DEFAULT_MASTER_REPO)


def build() -> None:
    """Run manual build on workstation"""
    pkgdirs = detect_changed_packages()
    pkgs_lists = [buildpkg(pd) for pd in pkgdirs]
    print("Outputs:")
    for pli in pkgs_lists:
        for p in pli:
            print(p)


def upload(fi, args, repo) -> None:
    """Upload to Bintray"""
    assert repo, "Please specify a repository"
    assert fi.is_file()
    pname, pver, arch = fi.name.split("_")
    btuser = getenv("BINTRAY_USERNAME")
    assert btuser, "Missing BINTRAY_USERNAME"
    auth = HTTPBasicAuth(btuser, getenv("BINTRAY_API_KEY"))
    dist = "unstable"
    url = (
        f"{BINTRAY_API}/content/{args.org}/{repo}/{pname}/{pver}/{fi.name};"
        f"deb_distribution={dist};deb_component=main;deb_architecture=amd64;publish=1"
    )
    with open(fi, "rb") as f:
        resp = requests.put(url, auth=auth, data=f)

    if not resp.ok:
        print(f"Error {resp.text} when calling {resp.request.url}")
        sys.exit(1)


def delete_bintray_package(args, extra) -> None:
    """Delete package from Bintray"""
    btuser = getenv("BINTRAY_USERNAME")
    assert btuser
    auth = HTTPBasicAuth(btuser, getenv("BINTRAY_API_KEY"))
    filename = extra[0]
    assert filename.endswith(".deb")
    assert args.repo, "Please specify a repository"
    url = f"{BINTRAY_API}/content/{args.org}/{args.repo}/{filename}"
    resp = requests.delete(url, auth=auth)
    if not resp.ok:
        print(f"Error {resp.text} when calling {resp.request.url}")
        sys.exit(1)


def main():
    ap = ArgumentParser(description=__doc__)
    ap.add_argument(
        "action", choices=("upload", "scan", "ci", "build", "delete_from_bintray")
    )
    ap.add_argument(
        "-r", "--repo", default=None, help="Bintray repository name"
    )
    ap.add_argument("-o", "--org", default=DEFAULT_ORG, help="Bintray org name")
    args, extra = ap.parse_known_args()
    if args.action == "ci":
        ci(args)
    elif args.action == "scan":
        for p in sorted(detect_changed_packages()):
            print(p.as_posix())
    elif args.action == "upload":
        for fn in extra:
            upload(Path(fn), args, args.repo)
    elif args.action == "delete_from_bintray":
        delete_bintray_package(args, extra)
    elif args.action == "build":
        build()


if __name__ == "__main__":
    main()
