lists:
	curl -O https://ooni.torproject.org/inputs/input-pack.tar.gz
	tar xzf input-pack.tar.gz
	rm input-pack.tar.gz
	mv input-pack/alexa-top-1k.txt 37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1
	mv input-pack/alexa-top-1m.txt e0611ecd28bead38a7afeb4dda8ae3449d0fc2e1ba53fa7355f2799dce9af290
	rm -rf input-pack
