version: 0.2
env:
  variables:
    OONI_CODE_PATH: api/fastapi/
    IMAGE_NAME: ooni/dataapi

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - python -m pip install hatch

  pre_build:
    commands:
      - aws --version
      - echo "Logging in to ECR"
      - aws secretsmanager get-secret-value --secret-id DOCKER_HUB_PASSWORD --query SecretString --output text | docker login --username ooni --password-stdin

  build:
    commands:
      - PROJECT_ROOT=$(pwd)
      - cd $OONI_CODE_PATH
      - echo "Installing project dependencies with poetry..."
      - make test
      - echo "Building and tagging Docker image..."
      - make docker-build

  post_build:
    commands:
      - echo "Build complete at $(date)"
      - echo "Pushing Docker images..."
      - make docker-push
      - make imagedefinitions.json

artifacts:
  files: imagedefinitions.json
