#!/bin/bash
DOCS_ROOT=dist/docs/
REPO_NAME="ooni/backend"
MAIN_BRANCH="master"
COMMIT_HASH=$(git rev-parse --short HEAD)

mkdir -p $DOCS_ROOT

strip_title() {
    # Since the title is already present in the frontmatter, we need to remove
    # it to avoid duplicate titles
    local infile="$1"
    cat $infile | awk 'BEGIN{p=1} /^#/{if(p){p=0; next}} {print}'
}

generate_doc() {
    local output_file="$1"
    local title="$2"
    local description="$3"
    local slug="$4"
    local input_file="$5"

    cat <<EOF>"$DOCS_ROOT/$output_file"
---
# Do not edit! This file is automatically generated
# version: $REPO_NAME/$input_file:$COMMIT_HASH
title: $title
description: $description
slug: $slug
---
EOF
    echo "[edit file](https://github.com/$REPO_NAME/edit/$MAIN_BRANCH/$input_file)" >> "$DOCS_ROOT/$output_file"
    strip_title "$input_file" >> "$DOCS_ROOT/$output_file"
}

# Generate documentation files
generate_doc "00-index.md" "OONI Backend" "OONI Backend documentation" "backend" "README.md"
generate_doc "01-ooniapi-guidelines.md" "OONI API Guidelines" "OONI API development guidelines" "backend/ooniapi" "ooniapi/README.md"
generate_doc "02-ooniapi-services.md" "OONI API Services" "OONI API Services documentation" "backend/ooniapi/services" "docs/API.md"
generate_doc "03-test-helpers.md" "OONI Test Helpers" "OONI Test helpers documentation" "backend/test-helpers" "docs/TestHelpers.md"
generate_doc "04-backend-fastpath.md" "OONI Fastpath" "OONI Fastpath documentation" "backend/fastpath" "docs/Fastpath.md"
generate_doc "05-backend-measurement-uploader.md" "OONI Measurement Uploader" "OONI measurement uploader documentation" "backend/measurement-uploader" "docs/MeasurementUploader.md"
generate_doc "06-backend-systemd-timers.md" "Systemd Timers" "Systemd timers documentation" "backend/systemd-timers" "docs/SystemdTimers.md"
generate_doc "07-backend-analysis.md" "Backend Analysis" "Backend Analysis documentation" "backend/analysis" "docs/BackendAnalysis.md"
generate_doc "08-backend-database.md" "Database" "OONI Database schemas, guidelines and more" "backend/database" "docs/Database.md"
generate_doc "09-backend-other-components.md" "Other components" "Other components, nginx, jupyter notebooks, etc. " "backend/other-components" "docs/OtherComponents.md"
generate_doc "10-web-uis.md" "Web UIs" "Web UIs" "web-uis" "docs/WebUIs.md"
generate_doc "11-ci-cd.md" "CD/CI" "Continous Integration, Continous Delivery workflows" "backend/ci-cd" "docs/CI-CD.md"
generate_doc "12-bridges.md" "OONI Bridges" "OONI Bridges" "backend/bridges" "docs/Bridges.md"
