#!/bin/bash
docker compose run --rm api python3 ooniapi/app.py
if diff apispec.json docs/apispec.json; then
  echo docs/apispec.json is up to date
else
  echo "ERROR: apispec.json has changed"
  echo "Run tools/check_apispec_changes and update docs/apispec.json"
fi
