#!/bin/bash -ex

id=$(docker run --rm --detach --net=none -e POSTGRES_USER=oopguser postgres:9.6)
until docker exec -i $id psql -U oopguser -c 'select 1' >/dev/null; do
    sleep 0.5
done
if [ $# -eq 0 ]; then
    cat *.install.sql
else
    cat "$@"
fi | docker exec -i $id psql -U oopguser >/dev/null
docker exec -i $id pg_dump -U oopguser --schema-only
docker stop $id >/dev/null
