#!/bin/sh -ex

id=$(docker run --rm --detach --hostname spbmeta --name spbmeta -v "$PWD/tsv:/tsv:ro" -e POSTGRES_USER=oopguser postgres:9.6)
until docker exec -i $id psql -U oopguser -c 'select 1' >/dev/null; do
    sleep 0.5
done

cat *.install.sql | docker exec -i $id psql -U oopguser

for fname in tsv/*.tsv; do
    if [ -r "$fname" ]; then
        tbl=$(basename "$fname" .tsv)
        docker exec -i $id psql -U oopguser -c "TRUNCATE ${tbl}; COPY ${tbl} FROM '/tsv/${tbl}.tsv'"
    fi
done

docker inspect $id | jq --raw-output '.[].NetworkSettings.Networks.bridge.IPAddress'
