services:
  fastpath:
    build:
      context: .
      dockerfile: Dockerfile.fastpath
    container_name: ooni-fastpath 
    ports:
      - "5000:5000"
      - "8472:8472"
    environment:
      - CLICKHOUSE_HOST=clickhouse-server
      - CLICKHOUSE_PORT=8123
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      clickhouse-server:
        condition: service_healthy
        restart: true
    profiles:
      - default
      - all
      - test

  clickhouse-server:
    build:
      context: .
      dockerfile: Dockerfile.clickhouse
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    ports:
      - "9000:9000"
      - "8123:8123"
      - "9009:9009"
    volumes:
       - ./clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "default:default", "http://localhost:8123/?query=SELECT%201"]
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 10s
    profiles:
      - all
      - test

volumes:
  clickhouse-data:
