# automatically syched from: ooni/pm-tools
on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        if: github.event.action == 'opened'
        with:
          project-url: https://github.com/orgs/ooni/projects/31
          github-token: ${{ secrets.ADD_TO_PROJECT_GH_TOKEN }}

      - uses: actions/add-to-project@RELEASE_VERSION
        if: github.event.action == 'labeled' && startsWith(github.event.label.name, 'funder/')
        with:
          project-url: https://github.com/orgs/ooni/projects/33
          github-token: ${{ secrets.ADD_TO_PROJECT_GH_TOKEN }}
