name: Build deb packages
on: pull_request

jobs:
  build_deb_packages:
    runs-on: "ubuntu-20.04"
    container: debian:11
    steps:
      - name: Change Owner of Container Working Directory
        run: chown root:root .

      - name: Install git
        run: |
          apt-get update -q
          apt-get install -y git

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install depedencies
        run: |
          echo "deb http://deb.debian.org/debian bullseye-backports main" > /etc/apt/sources.list.d/backports.list
          apt-get update -q
          apt-get install -y --no-install-recommends git python3 python3-requests python3-gnupg s3cmd wget

      - name: Fetch debops-ci
        run: |
          wget https://raw.githubusercontent.com/ooni/sysadmin/master/tools/debops-ci
          chmod +x debops-ci

      - name: Build the package
        run: ./debops-ci --show-commands ci --bucket-name ooni-internal-deb
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEB_GPG_KEY: ${{ secrets.DEB_GPG_KEY }}
