name: test fastpath
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: debian:11
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          apt-get update
          apt-get -y --no-install-recommends install python3-boto3 python3-lz4 python3-psycopg2 python3-setuptools \
          python3-statsd python3-systemd python3-ujson nginx python3-pytest python3-yaml python3-gunicorn \
          python3-pytest-cov mypy python3-clickhouse-driver

      - name: Run mypy
        run: mypy --ignore-missing-imports af/fastpath/fastpath || true

      - name: Run tests
        run: |
          cd fastpath
          PYTHONPATH=. pytest-3 -v --cov=fastpath --cov-report=term \
          fastpath/tests/test_functional.py \
          fastpath/tests/test_functional_nodb.py \
          fastpath/tests/test_unit.py

      - name: Archive code coverage HTML pages
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: fastpath/htmlcov
